name: bear_app
description: 熊 — 安卓轻桌宠
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
